- name: Install stow
  become: true
  apt: name=stow
  tags:
    - install
    - dotfiles

- name: Clone .files
  ansible.builtin.git:
    repo: 'git@github.com:Cra1g01/.files.git'
    dest: "{{ lookup('env', 'HOME') }}/.files"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles

- name: Stow dotfiles
  shell: cd $HOME/.files && ./ubuntu
  tags:
    - install
    - dotfiles
