- name: Git setup email
  git_config:
    name: user.email
    scope: global
    value: "craig@ianlyn.co.uk"
  tags:
  - git

- name: Git setup name
  git_config:
    name: user.name
    scope: global
    value: "Craig Wightman"
  tags:
  - git