- name: Download and install fnm
  shell: curl -o- https://fnm.vercel.app/install | bash
  tags:
    - install
    - node

- name: Install Node 22
  shell: fnm install 22
  tags:
    - install
    - node
