- name: Install Node and npm
  become: true
  apt:
    name: ["nodejs", "npm"]
  tags:
    - install
    - node
  
- name: Install N
  become: true
  npm:
    name: n
    global: yes
  tags:
    - install
    - node

- name: Install Node 18
  become: true
  shell: n 18
  tags:
    - install
    - node
